import type { Metadata } from 'next'
import { Suspense } from 'react'
import { GlowEffect } from '@/components/layout/GlowEffect'
import { GalleryPageClient } from './GalleryPageClient'
import { getServerSupabase } from '@/lib/supabase'
import type { CommunityScene } from '@/app/api/community/gallery/route'

export const metadata: Metadata = {
  title: 'Community Gallery - insyte',
  description: 'Browse AI-generated simulations created by the insyte community.',
  openGraph: {
    title: 'Community Gallery - insyte',
    description: 'Browse AI-generated simulations created by the insyte community.',
  },
}

async function fetchInitialScenes(): Promise<{ scenes: CommunityScene[]; hasMore: boolean }> {
  const supabase = getServerSupabase()
  if (!supabase) return { scenes: [], hasMore: false }

  const { data, error } = await supabase
    .from('user_generated_scenes')
    .select('scene_slug, query, generated_at, scenes(title, type, hit_count)')
    .not('scene_slug', 'is', null)
    .not('query', 'is', null)
    .order('generated_at', { ascending: false })
    .range(0, 19)

  if (error) return { scenes: [], hasMore: false }

  const scenes: CommunityScene[] = (data ?? [])
    .filter((row) => row.scene_slug && row.scenes)
    .map((row) => {
      const scene = Array.isArray(row.scenes) ? row.scenes[0] : row.scenes
      return {
        slug: row.scene_slug!,
        title: scene?.title ?? row.scene_slug!,
        type: scene?.type ?? 'concept',
        query: row.query!,
        hit_count: scene?.hit_count ?? 0,
        generated_at: row.generated_at,
      }
    })

  return { scenes, hasMore: scenes.length === 20 }
}

function GalleryShell({ scenes, hasMore }: { scenes: CommunityScene[]; hasMore: boolean }) {
  return (
    <GalleryPageClient
      initialScenes={scenes}
      initialHasMore={hasMore}
      initialSort="recent"
    />
  )
}

export default async function GalleryPage() {
  const { scenes, hasMore } = await fetchInitialScenes()

  return (
    <div className="relative min-h-screen">
      <GlowEffect intensity="subtle" className="fixed" />

      <div className="relative z-10 mx-auto max-w-screen-xl px-4 sm:px-6 py-10 flex flex-col gap-8">
        {/* Header */}
        <div className="flex flex-col gap-2">
          <h1 className="font-headline font-extrabold text-4xl sm:text-5xl text-on-surface">
            Community Gallery
          </h1>
          <p className="text-base text-on-surface-variant max-w-lg">
            Simulations generated by the community. Explore what others are learning.
          </p>
        </div>

        <Suspense fallback={null}>
          <GalleryShell scenes={scenes} hasMore={hasMore} />
        </Suspense>
      </div>
    </div>
  )
}
