import type { Metadata } from 'next'
import { Suspense } from 'react'
import { GlowEffect } from '@/components/layout/GlowEffect'
import { GalleryPageClient } from './GalleryPageClient'
import { getServerSupabase } from '@/lib/supabase'
import type { CommunityScene } from '@/app/api/community/gallery/route'

export const metadata: Metadata = {
  title: 'Community Gallery - insyte',
  description: 'Browse AI-generated simulations created by the insyte community.',
  openGraph: {
    title: 'Community Gallery - insyte',
    description: 'Browse AI-generated simulations created by the insyte community.',
  },
}

async function fetchInitialScenes(): Promise<{
  scenes: CommunityScene[]
  hasMore: boolean
  totalCount: number
}> {
  const supabase = getServerSupabase()
  if (!supabase) return { scenes: [], hasMore: false, totalCount: 0 }

  const [pageResult, countResult] = await Promise.all([
    supabase
      .from('user_generated_scenes')
      .select('scene_slug, query, generated_at, scenes(title, type, hit_count)')
      .not('scene_slug', 'is', null)
      .not('query', 'is', null)
      .order('generated_at', { ascending: false })
      .range(0, 19),
    supabase
      .from('user_generated_scenes')
      .select('id', { count: 'exact', head: true })
      .not('scene_slug', 'is', null)
      .not('query', 'is', null),
  ])

  if (pageResult.error) return { scenes: [], hasMore: false, totalCount: 0 }

  const scenes: CommunityScene[] = (pageResult.data ?? [])
    .filter((row) => row.scene_slug && row.scenes)
    .map((row) => {
      const scene = Array.isArray(row.scenes) ? row.scenes[0] : row.scenes
      return {
        slug: row.scene_slug!,
        title: scene?.title ?? row.scene_slug!,
        type: scene?.type ?? 'concept',
        query: row.query!,
        hit_count: scene?.hit_count ?? 0,
        generated_at: row.generated_at,
      }
    })

  return {
    scenes,
    hasMore: scenes.length === 20,
    totalCount: countResult.count ?? 0,
  }
}

export default async function GalleryPage() {
  const { scenes, hasMore, totalCount } = await fetchInitialScenes()

  return (
    <div className="relative min-h-screen">
      <GlowEffect intensity="subtle" className="fixed" />

      <div className="relative z-10 mx-auto max-w-screen-xl px-4 sm:px-6 py-12 flex flex-col gap-10">

        {/* Hero header */}
        <div className="flex flex-col gap-3 max-w-2xl">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-widest text-primary/70 border border-primary/20 bg-primary/5 px-3 py-1 rounded-full">
              <span className="h-1.5 w-1.5 rounded-full bg-primary/60 animate-pulse" />
              Live community feed
            </span>
          </div>
          <h1 className="font-headline font-extrabold text-4xl sm:text-5xl text-on-surface leading-tight">
            Community{' '}
            <span className="gradient-text">Gallery</span>
          </h1>
          <p className="text-base text-on-surface-variant max-w-lg leading-relaxed">
            Simulations generated by the community. See what others are exploring and learning.
          </p>
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-outline-variant/30 via-primary/20 to-transparent" />

        <Suspense fallback={null}>
          <GalleryPageClient
            initialScenes={scenes}
            initialHasMore={hasMore}
            initialSort="recent"
            totalCount={totalCount}
          />
        </Suspense>
      </div>
    </div>
  )
}
