import { describe, it, expect } from 'vitest'
import { computeSceneGraphAtStep } from './compute'
import type { Scene } from '../types'

describe('scene-graph compute', () => {
  const dummyScene = {
    id: 's1',
    title: 'test',
    type: 'concept',
    layout: 'canvas-only',
    visuals: [
      {
        id: 'array-viz',
        type: 'array',
        initialState: { cells: [{ value: 42 }] }
      }
    ],
    steps: [
      {
        index: 0,
        actions: []
      },
      {
        index: 1,
        actions: [
          { target: 'array-viz', params: { cells: [{ value: 99 }] } }
        ]
      }
    ]
  } as unknown as Scene

  describe('computeSceneGraphAtStep', () => {
    it('computes initial graph correctly', () => {
      const graph = computeSceneGraphAtStep(dummyScene, 0, 800, 600)
      
      expect(graph.stepIndex).toBe(0)
      
      // Should have processed the array visual into layout nodes
      expect(graph.groups.has('array-viz')).toBe(true)
      
      // Node IDs are dynamically generated by arithmetic.ts (e.g. cell-0)
      const groupInfo = graph.groups.get('array-viz')!
      expect(groupInfo.nodeIds.length).toBe(1)
      
      const nodeId = groupInfo.nodeIds[0]!
      const nodeObj = graph.nodes.get(nodeId)!
      
      expect(nodeObj.type).toBe('array')
      expect(nodeObj.state).toEqual({ cells: [{ value: 42 }] })
    })

    it('computes mutated graph correctly at later step', () => {
      const graph = computeSceneGraphAtStep(dummyScene, 1, 800, 600)
      
      // Verify visual state advanced correctly
      const groupInfo = graph.groups.get('array-viz')!
      const nodeId = groupInfo.nodeIds[0]!
      const nodeObj = graph.nodes.get(nodeId)!
      
      // Since it's step 1, the SET action happened and value is 99
      expect(nodeObj.state).toEqual({ cells: [{ value: 99 }] })
    })
  })
})
