// ─── Spec Entry Types ─────────────────────────────────────────────────────────
// Internal TypeScript types that describe the shape of spec objects themselves.
// No Zod, no functions — pure data.

export type FieldSource =
  | 'ai:s1'
  | 'ai:s2'
  | 'ai:s3'
  | 'ai:s4'
  | 'assembly'
  | 'handcrafted'
  | 'ai:s1+s2'

export interface RootFieldEntry {
  source: FieldSource
  required: boolean
  description: string
  values?: string[]
}

export interface StateFieldEntry {
  type: 'string' | 'number' | 'boolean' | 'any' | 'enum' | 'array' | 'object' | 'recursive'
  required: boolean
  description?: string
  values?: string[]
  default?: unknown
  items?: Record<string, StateFieldEntry>
  fields?: Record<string, StateFieldEntry>
}

export interface VariantSpec {
  description?: string
  highlightValues: string[]
  defaultLayoutHint?: string
  generationRules?: string[]
}

export interface CanvasVisualSpecEntry {
  description: string
  defaultLayoutHint: string
  source: 'ai'
  state: Record<string, StateFieldEntry>
  generationRules: string[]
  variants?: Record<string, VariantSpec>
}

// ─── Root Field Spec ──────────────────────────────────────────────────────────

export const ROOT_FIELD_SPEC = {
  id: {
    source: 'assembly',
    required: true,
    description: 'Unique scene identifier (nanoid). Generated by assembly — never set in AI output or hand-crafted files.',
  },
  title: {
    source: 'ai:s1',
    required: true,
    description: 'Human-readable scene title shown in the UI.',
  },
  type: {
    source: 'ai:s1',
    required: true,
    description: 'Scene category determining layout and content style.',
    values: ['concept', 'dsa-trace', 'lld', 'hld'],
  },
  layout: {
    source: 'assembly',
    required: true,
    description: 'Page layout derived from type. Never set by AI or hand-crafted files. dsa-trace→code-left-canvas-right, concept→text-left-canvas-right, lld/hld→canvas-only.',
    values: ['canvas-only', 'code-left-canvas-right', 'text-left-canvas-right'],
  },
  description: {
    source: 'ai:s1',
    required: false,
    description: 'Short scene summary (1–2 sentences). Shown in preview cards.',
  },
  category: {
    source: 'ai:s1',
    required: false,
    description: 'Broad grouping for discovery (e.g. "Data Structures & Algorithms", "System Design").',
  },
  code: {
    source: 'handcrafted',
    required: false,
    description: 'Code block shown on the left panel (code-left-canvas-right layout). Never AI-generated. Only in DSA and some concept scenes.',
  },
  canvas: {
    source: 'ai:s1+s2',
    required: true,
    description: 'Canvas visual declarations (type + variant + id + layoutHint, Stage 1) merged with initialState (Stage 2).',
  },
  activeText: {
    source: 'ai:s1+s2',
    required: false,
    description: 'Single operation string overlaid at top-left of canvas. Presence declared in Stage 1; initialValue and per-step values generated in Stage 2.',
  },
  hud: {
    source: 'ai:s1+s2',
    required: false,
    description: 'Label-value counter pairs overlaid at top-right of canvas (max 3). Item definitions (id, label) declared in Stage 1; initialValue and per-step values generated in Stage 2.',
  },
  controls: {
    source: 'handcrafted',
    required: true,
    description: 'Interactive UI controls in the bottom bar. Never AI-generated. Assembly sets [] when absent.',
  },
  steps: {
    source: 'ai:s2',
    required: true,
    description: 'Sequential animation steps (1-based). Step 0 is always implicit — assembly creates it from initialState fields. Each step contains explanation, canvas/activeText/hud updates.',
  },
  popups: {
    source: 'ai:s3',
    required: true,
    description: 'Transient contextual annotation popups attached to canvas visual ids. IDs generated by assembly (nanoid) — never set in AI output.',
  },
  challenges: {
    source: 'ai:s4',
    required: false,
    description: 'Thought-exercises and mini-puzzles for the user to apply their learning.',
  },
  complexity: {
    source: 'ai:s4',
    required: false,
    description: 'Big-O complexity annotations. Example: { time: "O(n)", space: "O(n)" }.',
  },
} satisfies Record<string, RootFieldEntry>

// ─── Canvas Visual Spec ───────────────────────────────────────────────────────

export const CANVAS_VISUAL_SPEC = {
  linear: {
    description: 'Linear sequence. Use variant to specify which: "array" (indexed cells), "stack" (LIFO), "queue" (FIFO), "linked-list" (pointer chain).',
    defaultLayoutHint: 'linear-H',
    source: 'ai',
    state: {
      items: {
        type: 'array',
        required: true,
        description: 'Ordered list of elements.',
        items: {
          id:        { type: 'string', required: true,  description: 'Stable id for keyed animation.' },
          value:     { type: 'any',    required: true,  description: 'Element value (number, string, etc.)' },
          highlight: { type: 'string', required: false, description: 'Variant-scoped highlight token.' },
        },
      },
      pointers: {
        type: 'array',
        required: false,
        description: 'Named pointer arrows (e.g. i, j, lo, hi, prev, curr).',
        items: {
          index: { type: 'number', required: true,  description: 'Zero-based index the pointer points to.' },
          label: { type: 'string', required: true,  description: 'Pointer label (e.g. "i", "lo").' },
          color: { type: 'string', required: false, description: 'Optional hex color override.' },
        },
      },
      windowHighlight: {
        type: 'object',
        required: false,
        description: 'Sliding window bracket. start/end are inclusive zero-based indices.',
        fields: {
          start: { type: 'number', required: true },
          end:   { type: 'number', required: true },
        },
      },
    },
    generationRules: [
      'ZERO-STATE: initialState.items must be [] unless the algorithm truly starts with pre-filled data.',
      'FULL-SNAPSHOT: every step canvas update must include ALL items — never a delta/partial list.',
      'Set variant in the canvas declaration. Required: "array" | "stack" | "queue" | "linked-list".',
      'items[].id is required for stable keyed animation.',
      'windowHighlight must be an object { start: number, end: number }. Do NOT use an array.',
      'pointers must be an array of objects [{ index: number, label?: string }].',
    ],
    variants: {
      array: {
        description: 'Indexed horizontal cells. Use for input arrays, lookup tables, frequency arrays.',
        highlightValues: ['default', 'active', 'hit', 'insert', 'error'],
        defaultLayoutHint: 'linear-H',
        generationRules: [
          'highlight values: default | active | hit | insert | error',
          'Use pointers[] for index cursors (i, j, lo, hi). Use windowHighlight for sliding window.',
        ],
      },
      stack: {
        description: 'LIFO stack rendered bottom-to-top. items[0] = bottom, last item = top.',
        highlightValues: ['default', 'active', 'push', 'pop'],
        defaultLayoutHint: 'linear-V',
        generationRules: [
          'highlight values: default | active | push | pop',
          'Items are ordered bottom-to-top. Push appends to end. Pop removes from end.',
        ],
      },
      queue: {
        description: 'FIFO queue. items[0] = front (exits first), last = back (enters last).',
        highlightValues: ['default', 'active', 'enqueue', 'dequeue'],
        defaultLayoutHint: 'linear-H',
        generationRules: [
          'highlight values: default | active | enqueue | dequeue',
          'Enqueue appends to end. Dequeue removes from front.',
        ],
      },
      'linked-list': {
        description: 'Singly linked list. Edges auto-rendered between adjacent items. HEAD = items[0].',
        highlightValues: ['default', 'active', 'insert', 'delete'],
        defaultLayoutHint: 'linear-H',
        generationRules: [
          'highlight values: default | active | insert | delete',
          'Edges between adjacent nodes are auto-generated — do not include edge data.',
          'items[0] is always HEAD. No headId needed.',
        ],
      },
    },
  },

  map: {
    description: 'Key-value map. Use for hash tables, memos, frequency maps, adjacency maps.',
    defaultLayoutHint: 'hashmap-buckets',
    source: 'ai',
    state: {
      entries: {
        type: 'array',
        required: true,
        description: 'Map entries as an ordered list.',
        items: {
          id:        { type: 'string', required: true,  description: 'Stable id for keyed animation.' },
          key:       { type: 'string', required: true,  description: 'Map key (always stringified).' },
          value:     { type: 'string', required: true,  description: 'Map value (always stringified).' },
          highlight: { type: 'enum',   required: false, values: ['default', 'insert', 'hit', 'remove'], default: 'default' },
        },
      },
    },
    generationRules: [
      'ZERO-STATE: initialState.entries must be [].',
      'FULL-SNAPSHOT: every step canvas update must include ALL entries.',
      'highlight values: default | insert | hit | remove',
      'Both key and value must be strings (stringify numbers).',
    ],
  },

  tree: {
    description: 'Tree with flat node array. Use variant "binary" for BST/search trees, "trie" for prefix trees, "recursion" for recursive call trees.',
    defaultLayoutHint: 'dagre-TB',
    source: 'ai',
    state: {
      nodes: {
        type: 'array',
        required: true,
        description: 'Flat list of tree nodes.',
        items: {
          id:        { type: 'string', required: true,  description: 'Stable id for keyed animation.' },
          value:     { type: 'string', required: true,  description: 'Display label. For recursion variant: call label e.g. "fib(4)".' },
          children:  { type: 'array',  required: true,  description: 'Array of child node IDs ([] for leaves, never omit).' },
          highlight: { type: 'string', required: false, description: 'Variant-scoped highlight token.' },
          result:    { type: 'string', required: false, description: 'Return value. Only for recursion variant (e.g. "= 3").' },
        },
      },
      rootId: {
        type: 'string',
        required: false,
        description: 'ID of the root node (null if tree is empty).',
      },
    },
    generationRules: [
      'Step canvas uses sparse overlay — never re-emit topology fields (value, children, isEnd).',
      'nodeStates: Record<nodeId, {highlight?, result?}>. Only list nodes with non-default state.',
      'newNodes: [{id, value, children}] — declare only when a node first appears. children: [] for leaves.',
      'updateNodes: [{id, children?, ...}] — declare only when topology changes (e.g. rewire after insert).',
      'updateRoot: newRootId — use only when rootId changes (e.g. tree rotation).',
      'Unlisted nodes: highlight resets to "default", result persists from last assignment.',
      'Set variant in the canvas declaration: "binary" (default), "trie" for prefix trees, or "recursion" for call trees.',
      'Nodes value MUST be a string. Stringify numbers (e.g. "5").',
      'rootId can be null if the tree starts empty.',
    ],
    variants: {
      binary: {
        description: 'Binary search/decision tree. Max 2 children per node.',
        highlightValues: ['default', 'active', 'found', 'visited'],
        defaultLayoutHint: 'dagre-TB',
        generationRules: [
          'highlight values: default | active | found | visited',
          'Max 2 children per node. children[] may have 0, 1, or 2 IDs.',
        ],
      },
      trie: {
        description: 'Prefix tree. N-ary (arbitrary children). Edge labels show characters. isEnd marks word boundaries.',
        highlightValues: ['default', 'active', 'found'],
        defaultLayoutHint: 'dagre-TB',
        generationRules: [
          'highlight values: default | active | found',
          'isEnd: true marks nodes where a valid word ends — renders a double ring.',
          'value: "" for the root node. value: single character for all other nodes.',
          'Edge label shown on each edge is the character of the child node.',
          'N-ary: children[] can have any number of IDs (one per unique next-character).',
        ],
      },
      recursion: {
        description: 'Recursive call tree. N-ary (any number of children). Shows return values.',
        highlightValues: ['default', 'active', 'returned', 'memoized'],
        defaultLayoutHint: 'tree-RT',
        generationRules: [
          'highlight values: default | active | returned | memoized',
          'Use result field for return value shown below node (e.g. "= 3").',
          'memoized highlight: node computed from cache (shows strikethrough and dashed edges).',
          'N-ary: children[] can have any number of IDs.',
        ],
      },
    },
  },

  graph: {
    description: 'General directed/undirected graph. Both nodes[] and edges[] required. Use variant "weighted" for Dijkstra/Prim/Kruskal algorithms.',
    defaultLayoutHint: 'dagre-LR',
    source: 'ai',
    state: {
      nodes: {
        type: 'array',
        required: true,
        description: 'Graph nodes.',
        items: {
          id:        { type: 'string', required: true,  description: 'Stable node id.' },
          label:     { type: 'string', required: true,  description: 'Display label.' },
          highlight: { type: 'enum',   required: false, values: ['default', 'active', 'visited', 'found'], default: 'default' },
        },
      },
      edges: {
        type: 'array',
        required: true,
        description: 'Graph edges.',
        items: {
          id:        { type: 'string',  required: true,  description: 'Unique edge id.' },
          from:      { type: 'string',  required: true,  description: 'Source node id.' },
          to:        { type: 'string',  required: true,  description: 'Target node id.' },
          label:     { type: 'string',  required: false, description: 'Edge weight or label.' },
          directed:  { type: 'boolean', required: false, description: 'Whether arrow is shown.' },
          highlight: { type: 'enum',    required: false, values: ['default', 'active'], default: 'default' },
        },
      },
    },
    generationRules: [
      'Step canvas uses sparse overlay — never re-emit topology fields (label, from, to, weight, directed).',
      'nodeStates: Record<nodeId, {highlight?, distance?}>. Only list nodes with non-default state.',
      'edgeStates: Record<edgeId, {highlight?}>. Only list edges with non-default state.',
      'newNodes: [{id, label, ...}] — declare only when a node first appears.',
      'updateNodes: [{id, ...partialTopology}] — declare only when topology changes.',
      'newEdges / updateEdges: same pattern as nodes.',
      'Unlisted nodes: highlight resets to "default", distance persists from last assignment.',
      'Unlisted edges: highlight resets to "default".',
      'Edge id must be unique across all edges.',
      'node highlight values: default | active | visited | found',
      'edge highlight values: default | active',
    ],
    variants: {
      weighted: {
        description: 'Weighted graph for Dijkstra, Prim\'s, Kruskal\'s. Renders weight badges on edges and distance labels on nodes.',
        highlightValues: ['default', 'active', 'relaxed', 'min-edge', 'in-tree', 'rejected'],
        defaultLayoutHint: 'dagre-TB',
        generationRules: [
          'node highlight values: default | active | visited | source | settled | found',
          'edge highlight values: default | active | relaxed | min-edge | in-tree | rejected',
          'edges[].weight is REQUIRED (number) — drives the rendered weight badge.',
          'nodes[].distance is optional (string: "∞", "0", "7") — shown as a badge below node.',
          'source: starting node. settled: shortest path finalised. relaxed: distance updated.',
          'min-edge: currently selected minimum. in-tree: included in MST. rejected: discarded.',
        ],
      },
    },
  },

  grid: {
    description: '2D grid. Use variant "pathfinding" for maze/island problems, "dp" for dynamic programming tables.',
    defaultLayoutHint: 'grid-2d',
    source: 'ai',
    state: {
      rows: {
        type: 'number',
        required: true,
        description: 'Row count.',
      },
      cols: {
        type: 'number',
        required: true,
        description: 'Column count.',
      },
      cells: {
        type: 'array',
        required: true,
        description: '2D array: cells[row][col]. No per-cell id — positional keying.',
        items: {
          value:     { type: 'any',    required: true,  description: 'Cell value (number, string, or null for unfilled).' },
          highlight: { type: 'string', required: false, description: 'Variant-scoped highlight token.' },
        },
      },
      rowLabels: {
        type: 'array',
        required: false,
        description: 'Optional row header labels. Used in "dp" variant.',
        items: { type: { type: 'string', required: true } },
      },
      colLabels: {
        type: 'array',
        required: false,
        description: 'Optional column header labels. Used in "dp" variant.',
        items: { type: { type: 'string', required: true } },
      },
      currentCell: {
        type: 'object',
        required: false,
        description: 'Active cursor position. Used in "pathfinding" variant.',
        fields: {
          row: { type: 'number', required: true },
          col: { type: 'number', required: true },
        },
      },
    },
    generationRules: [
      'FULL-SNAPSHOT: every step canvas update must include ALL cells in ALL rows.',
      'Set variant in the canvas declaration: "pathfinding" or "dp".',
      'rows and cols must be set in every canvas update.',
    ],
    variants: {
      pathfinding: {
        description: 'Grid for path-finding, island, or maze problems.',
        highlightValues: ['default', 'active', 'visited', 'wall', 'path', 'start', 'end'],
        defaultLayoutHint: 'grid-2d',
        generationRules: [
          'highlight values: default | active | visited | wall | path | start | end',
          'Use highlight:"wall" for blocked cells, highlight:"path" for the solution path.',
          'Use currentCell for the active DFS/BFS cursor.',
        ],
      },
      dp: {
        description: '2D dynamic programming table.',
        highlightValues: ['default', 'active', 'filled', 'source'],
        defaultLayoutHint: 'grid-2d',
        generationRules: [
          'highlight values: default | active | filled | source',
          'Initialize unfilled cells with value: null and no highlight.',
          'Use rowLabels/colLabels for axis labels.',
        ],
      },
    },
  },

  chart: {
    description: 'Bar chart for quantitative comparison. Use for sorting algorithms, frequency distributions, load comparisons.',
    defaultLayoutHint: 'chart-bar',
    source: 'ai',
    state: {
      bars: {
        type: 'array',
        required: true,
        description: 'Ordered list of bars, left to right.',
        items: {
          id:        { type: 'string',  required: true,  description: 'Stable id for keyed animation.' },
          value:     { type: 'number',  required: true,  description: 'Numeric value — determines bar height.' },
          label:     { type: 'string',  required: false, description: 'Label shown below bar.' },
          highlight: { type: 'string',  required: false, description: 'Variant-scoped highlight token.' },
        },
      },
      maxValue: {
        type: 'number',
        required: false,
        description: 'Explicit scale ceiling. Auto-derived from max(bars[].value) if omitted.',
      },
    },
    generationRules: [
      'FULL-SNAPSHOT: every step canvas update must include ALL bars.',
      'bars[].id is required for stable keyed animation — use consistent IDs across steps.',
      'bars[].value is the raw number — never normalise it, the renderer scales automatically.',
      'highlight values: default | active | comparing | sorted | pivot',
      'Set maxValue in initialState to fix the scale across all steps (prevents scale jumping).',
    ],
    variants: {
      bar: {
        description: 'Vertical bar chart. Heights proportional to value, animated between steps.',
        highlightValues: ['default', 'active', 'comparing', 'sorted', 'pivot'],
        defaultLayoutHint: 'chart-bar',
        generationRules: [
          'highlight values: default | active | comparing | sorted | pivot',
          'active: bar currently being examined. comparing: being compared with active.',
          'sorted: bar in final correct position. pivot: the pivot/partition element.',
        ],
      },
    },
  },

  'system-diagram': {
    description: 'System architecture diagram with components and connections. Use for LLD/HLD/network explanations.',
    defaultLayoutHint: 'dagre-LR',
    source: 'ai',
    state: {
      components: {
        type: 'array',
        required: true,
        description: 'System components (servers, databases, etc.).',
        items: {
          id:       { type: 'string', required: true,  description: 'Stable component id.' },
          label:    { type: 'string', required: true,  description: 'Display name.' },
          icon:     { type: 'enum',   required: true,  values: ['server', 'database', 'mobile', 'web', 'compute', 'cloud', 'shield', 'layers', 'zap'] },
          status:   { type: 'enum',   required: true,  values: ['normal', 'active', 'overloaded', 'dead'], default: 'normal' },
          sublabel: { type: 'string', required: false, description: 'Secondary label (e.g. port, region, tech).' },
        },
      },
      connections: {
        type: 'array',
        required: true,
        description: 'Directed connections between components.',
        items: {
          id:     { type: 'string',  required: false, description: 'Optional stable id for future sparse overlay support.' },
          from:   { type: 'string',  required: true,  description: 'Source component id.' },
          to:     { type: 'string',  required: true,  description: 'Target component id.' },
          active: { type: 'boolean', required: true,  description: 'Whether data is flowing on this connection right now.' },
          style:  { type: 'enum',    required: false, values: ['solid', 'dashed', 'dotted'], default: 'solid' },
          label:  { type: 'string',  required: false, description: 'Connection label (e.g. "HTTPS", "TCP:5432").' },
        },
      },
    },
    generationRules: [
      'Step canvas uses sparse overlay — never re-emit topology fields (label, icon, sublabel, from, to, style).',
      'componentStates: Record<componentId, {status?}>. Unlisted → status: "normal".',
      'connectionStates: Record<connectionId, {active?}>. Unlisted → active: false.',
      'newComponents and updateComponents must be an ARRAY of objects: [{id, ...}]. Never a record/object.',
      'newConnections and updateConnections must be an ARRAY of objects: [{id, from, to, ...}].',
      'CHOREOGRAPHY RULE: when a call travels A→B→C, all three components must appear in componentStates with status "active" AND all edges in connectionStates with active:true simultaneously in that step.',
      'component status values: normal | active | overloaded | dead',
      'icon values: server | database | mobile | web | compute | cloud | shield | layers | zap',
      'Use layoutHint "ring" for circular topologies (consistent hashing, round-robin scheduling).',
    ],
  },
} satisfies Record<string, CanvasVisualSpecEntry>

// ─── Active Text Spec ─────────────────────────────────────────────────────────

export const ACTIVE_TEXT_SPEC = {
  description: 'Single operation string overlaid at top-left of canvas. Changes per step to describe what the algorithm is doing right now.',
  position: 'top-left canvas overlay',
  initialValueField: 'initialValue',
  stepUpdateField: 'activeText',
  generationRules: [
    'PERSISTENCE: once set to a real value, never reset to placeholder text mid-flow.',
    'SEMANTIC: text should describe what the algorithm is doing right now, not what it did.',
    'Never emit empty string — omit the field entirely if no update needed for this step.',
    'Keep text concise: one equation, one decision, or one state description.',
  ],
}

// ─── HUD Spec ─────────────────────────────────────────────────────────────────

export const HUD_SPEC = {
  description: 'Label-value pairs overlaid at top-right of canvas. For numeric counters or short status strings.',
  position: 'top-right canvas overlay',
  maxItems: 3,
  valueTypes: ['string', 'number'] as const,
  generationRules: [
    'Maximum 3 HUD items per scene. 0–2 is preferred in practice.',
    'Use HUD for numeric counters (i, comparisons, depth) or short status strings (found: true).',
    'Do not duplicate information already in activeText or the step explanation.',
    'HUD values must be string or number — no objects or arrays.',
    'Partial updates: in step.hud, only include hud items being changed. Previous values persist.',
  ],
}

// ─── Step Spec ────────────────────────────────────────────────────────────────

export const STEP_SPEC = {
  fields: {
    index: {
      required: true,
      source: 'ai:s2' as FieldSource,
      description: '1-based integer. Step 0 is always implicit (initial state from initialState fields). Never include index:0 in steps[].',
    },
    explanation: {
      required: true,
      source: 'ai:s2' as FieldSource,
      description: 'Narrative block for this step. heading + body are required. callout is optional.',
    },
    activeText: {
      required: false,
      source: 'ai:s2' as FieldSource,
      description: 'Updated operation string. Omit if unchanged from previous step.',
    },
    hud: {
      required: false,
      source: 'ai:s2' as FieldSource,
      description: 'Partial HUD update: object keyed by hud item id with updated value. Omit if no HUD items change this step.',
    },
    canvas: {
      required: false,
      source: 'ai:s2' as FieldSource,
      description: 'Per-visual-id full-state snapshots. Omit a visual if its state does not change this step.',
    },
  },
  rules: [
    'Step 0 is synthetic — assembly creates it from initialState fields. Never include index:0 in steps[].',
    'Sequential primitives (linear, map, grid, chart): canvas entries must be FULL STATE SNAPSHOTS.',
    'Identity-based primitives (graph, tree, system-diagram): canvas entries use topology-state split. Write nodeStates/edgeStates/componentStates/connectionStates for state. Use newNodes/updateNodes etc. only when structure changes. Never re-emit topology fields in steps.',
    'canvas entry keys must only reference IDs declared in canvas[] at scene level.',
    'hud entry keys must only reference IDs declared in hud[] at scene level.',
    'explanation.heading and explanation.body are always required on every step.',
  ],
}

// ─── Entity Step Field Semantics ─────────────────────────────────────────────
// Defines how each field on identity-based primitive entities behaves across steps.
// Used by the step-engine to know what to reset vs. accumulate.

export const ENTITY_STEP_FIELD_SEMANTICS = {
  ephemeral: {
    description: 'Resets to default each step if not listed in step overlay.',
    fields: {
      'graph.nodes.highlight':             { default: 'default' },
      'graph.edges.highlight':             { default: 'default' },
      'tree.nodes.highlight':              { default: 'default' },
      'system-diagram.components.status':  { default: 'normal'  },
      'system-diagram.connections.active': { default: false      },
    },
  },
  accumulated: {
    description: 'Persists in registry from last assignment. Write only when the value changes.',
    fields: {
      'graph.nodes.distance': { initialDefault: '∞'   },
      'tree.nodes.result':    { initialDefault: null   },
    },
  },
} as const

// ─── Popup Spec ───────────────────────────────────────────────────────────────

export const POPUP_SPEC = {
  description: 'Transient contextual annotation popup attached to a canvas visual.',
  fields: {
    id: {
      source: 'assembly' as FieldSource,
      description: 'nanoid — generated by assembly. Never set in AI output or hand-crafted files.',
    },
    attachTo: {
      source: 'ai:s3' as FieldSource,
      description: 'Must reference a canvas visual id declared in canvas[].',
    },
    text: {
      source: 'ai:s3' as FieldSource,
      description: 'Popup body text.',
    },
    showAtStep: {
      source: 'ai:s3' as FieldSource,
      description: '1-based step index when the popup appears.',
    },
    hideAtStep: {
      source: 'ai:s3' as FieldSource,
      description: 'Required. 1-based step index when the popup disappears. If omitted popup never hides.',
    },
    style: {
      source: 'ai:s3' as FieldSource,
      description: 'Visual style of the popup.',
      values: ['info', 'warning', 'success', 'insight'],
    },
  },
  maxPopups: 6,
  removedFields: ['anchor', 'targetPoint', 'showWhen'],
}
